name: deriv_chart
description: Chart for multiplier flutter app.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  deriv_technical_analysis:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_technical_analysis
      ref: dev

  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  deriv_lint:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_lint
      ref: dev

  build_runner: ^2.4.9
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/icons/
    - assets/icons/symbols/

flutter_intl:
  main_locale: en
  enabled: true
  class_name: ChartLocalization
